version: '3.8'

services:

  llama:
    image: nvcr.io/nim/meta/llama-3.1-70b-instruct:latest
    ports:
      - "8000:8000"
    environment:
      - NGC_API_KEY=${NGC_API_KEY}
    volumes:
      - ${LOCAL_NIM_CACHE}:/opt/nim/.cache
    user: "${UID:-1000}"
    shm_size: "16gb"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0', '1']
              capabilities: [gpu]
    restart: "no"
    networks:
      - shopping-network

  nvclip:
    image: nvcr.io/nim/nvidia/nvclip:2.0.0
    ports:
      - "8002:8000"
    environment:
      - NGC_API_KEY=${NGC_API_KEY}
    volumes:
      - ${LOCAL_NIM_CACHE}:/opt/nim/.cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['2']
              capabilities: [gpu]
    restart: "no"
    networks:
      - shopping-network

  embedqa:
    image: nvcr.io/nim/nvidia/nv-embedqa-e5-v5:1.6
    ports:
      - "8001:8000"
    environment:
      - NGC_API_KEY=${NGC_API_KEY}
    volumes:
      - ${LOCAL_NIM_CACHE}:/opt/nim/.cache
    user: "${UID:-1000}"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['2']
              capabilities: [gpu]
    restart: "no"
    networks:
      - shopping-network

  content:
    image: nvcr.io/nim/nvidia/llama-3.1-nemoguard-8b-content-safety:1.10.1
    ports:
      - "8003:8000"
    environment:
      - NGC_API_KEY=${NGC_API_KEY}
      - NIM_KVCACHE_PERCENT=.4
    volumes:
      - ${LOCAL_NIM_CACHE}:/opt/nim/.cache
    user: "${UID:-1000}"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['2']
              capabilities: [gpu]
    restart: "no"
    networks:
      - shopping-network

  topic_control:
    image: nvcr.io/nim/nvidia/llama-3.1-nemoguard-8b-topic-control:1.0.0
    ports:
      - "8004:8000"
    environment:
      - NGC_API_KEY=${NGC_API_KEY}
      - NIM_KVCACHE_PERCENT=.4
    volumes:
      - ${LOCAL_NIM_CACHE}:/opt/nim/.cache
    user: "${UID:-1000}"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['3']
              capabilities: [gpu]
    restart: "no"
    networks:
      - shopping-network

networks:
  shopping-network:
    driver: bridge
    name: retail-shopping-assistant_shopping-network

