text_embed_port: "http://embedqa:8000/v1"
text_model_name: "nvidia/nv-embedqa-e5-v5" 
image_embed_port: "http://nvclip:8000/v1"
image_model_name: "nvidia/nvclip"
db_port: "http://milvus:19530" 
db_name: "shopping_advisor_db"
sim_threshold: 0.5
text_collection: "shopping_advisor_text_db"
image_collection: "shopping_advisor_image_db"
#data_source: "/app/shared/data/products.csv"
data_source: "/app/shared/data/products_extended.csv"
