db_port: "http://milvus:19530" 
db_name: "shopping_advisor_db"
catalog_id: "fashion_products"
sim_threshold: 0.3
text_collection: "shopping_advisor_text_db"
image_collection: "shopping_advisor_image_db"
data_source: "/app/shared/data/enriched_products.jsonl"
schema_source: "/app/shared/data/enriched_products.schema.yaml"
