models:
  - type: main
    engine: nim
    model: meta/llama-3.1-70b-instruct
      
  - type: content_safety
    parameters:
      base_url: https://integrate.api.nvidia.com/v1

  - type: topic_control
    parameters:
      base_url: https://integrate.api.nvidia.com/v1