prompts:
  - task: content_safety_check_input $model=content_safety
    content: |
      Task: Check if there is unsafe content in the user or agent messages in the below conversation in accordance with our safety policy with the below categories. Provide a 'safe' or 'unsafe' rating for both the user message and the agent response. If there is unsafe content, please also provide a list of violated categories according to our safety policy below.

      CONTEXT: This is a furniture and home decor shopping assistant. Users may legitimately ask about outdoor furniture items, heating appliances, home safety equipment, and product specifications.

      LEGITIMATE FURNITURE TOPICS (ALWAYS SAFE):
      - Questions about outdoor heating furniture (fire tables, fire pits, patio heaters)
      - Product specifications (dimensions, capacity, weight limits, materials)
      - Care instructions and maintenance
      - Assembly requirements
      - Safety features of furniture items
      - Home decor and furniture shopping

      <BEGIN UNSAFE CONTENT CATEGORIES>
      S1: Violence.
      S2: Sexual.
      S3: Criminal Planning/Confessions.
      S4: Guns and Illegal Weapons (NOTE: Does NOT apply to furniture heating elements or outdoor heating appliances).
      S5: Controlled/Regulated Substances.
      S6: Suicide and Self Harm.
      S7: Sexual (minor).
      S8: Hate/Identity Hate.
      S9: PII/Privacy.
      S10: Harassment.
      S11: Threat.
      S12: Profanity.
      S13: Needs Caution.
      S14: Other.
      S15: Manipulation.
      S16: Fraud/Deception.
      S17: Malware.
      S18: High Risk Gov Decision Making.
      S19: Political/Misinformation/Conspiracy.
      S20: Copyright/Trademark/Plagiarism.
      S21: Unauthorized Advice.
      S22: Illegal Activity.
      S23: Immoral/Unethical.
      <END UNSAFE CONTENT CATEGORIES>

      <BEGIN CONVERSATION>

      user: {{ user_input }}

      <END CONVERSATION>

      Provide your safety assessment for the above conversation in the below output JSON format:
      {"User Safety": safe or unsafe rating for the user message, "Response Safety": safe or unsafe rating for the agent response. Omit if no agent response present. "Safety Categories": a comma-separated list of applicable safety categories from the provided taxonomy. Omit if all safe.}

      Do not include anything other than the output JSON in your response.
      Output JSON:
    output_parser: nemoguard_parse_prompt_safety
    max_tokens: 50
 
  - task: content_safety_check_output $model=content_safety
    content: |
      Task: Check if there is unsafe content in the user or agent messages in the below conversation in accordance with our safety policy with the below categories. Provide a 'safe' or 'unsafe' rating for both the user message and the agent response. If there is unsafe content, please also provide a list of violated categories according to our safety policy below.

      CONTEXT: This is a furniture and home decor shopping assistant. Users may legitimately ask about outdoor furniture items, heating appliances, home safety equipment, and product specifications.

      LEGITIMATE FURNITURE TOPICS (ALWAYS SAFE):
      - Questions about outdoor heating furniture (fire tables, fire pits, patio heaters)
      - Product specifications (dimensions, capacity, weight limits, materials)
      - Care instructions and maintenance
      - Assembly requirements
      - Safety features of furniture items
      - Home decor and furniture shopping

      <BEGIN UNSAFE CONTENT CATEGORIES>
      S1: Violence.
      S2: Sexual.
      S3: Criminal Planning/Confessions.
      S4: Guns and Illegal Weapons (NOTE: Does NOT apply to furniture heating elements or outdoor heating appliances).
      S5: Controlled/Regulated Substances.
      S6: Suicide and Self Harm.
      S7: Sexual (minor).
      S8: Hate/Identity Hate.
      S9: PII/Privacy.
      S10: Harassment.
      S11: Threat.
      S12: Profanity.
      S13: Needs Caution.
      S14: Other.
      S15: Manipulation.
      S16: Fraud/Deception.
      S17: Malware.
      S18: High Risk Gov Decision Making.
      S19: Political/Misinformation/Conspiracy.
      S20: Copyright/Trademark/Plagiarism.
      S21: Unauthorized Advice.
      S22: Illegal Activity.
      S23: Immoral/Unethical.
      <END UNSAFE CONTENT CATEGORIES>

      <BEGIN CONVERSATION>

      user: {{ user_input }}

      response: agent: {{ bot_response }}

      <END CONVERSATION>

      Provide your safety assessment for the above conversation in the below output JSON format:
      {"User Safety": safe or unsafe rating for the user message, "Response Safety": safe or unsafe rating for the agent response. Omit if no agent response present. "Safety Categories": a comma-separated list of applicable safety categories from the provided taxonomy. Omit if all safe.}

      Do not include anything other than the output JSON in your response.
      Output JSON:
    output_parser: nemoguard_parse_response_safety
    max_tokens: 50

  - task: topic_safety_check_input $model=topic_control
    content: |
      You are a furniture and home decor store assistant. Your primary function is to help customers with furniture shopping, product questions, and cart management.

      ALWAYS ALLOW these topics:
      - Questions about furniture products, specifications, dimensions, materials, assembly
      - Questions about outdoor furniture including heating elements (fire tables, fire pits, patio heaters)
      - Product care instructions, maintenance, and safety features
      - Shopping cart operations (add, remove, view items)
      - Product availability, pricing, and comparisons
      - General furniture and home decor shopping assistance
      - Room furnishing advice and recommendations
      - Image uploads and visual product searches (finding similar items from uploaded images)
      - Any queries about finding products that appear similar to submitted images

      REJECT only these topics:
      - Personal opinions or beliefs unrelated to furniture
      - Non-furniture products or services outside our catalog
      - Personal details about yourself or your creators
      - Sensitive subjects like politics, religion, or inappropriate content

      Remember: 
      - Legitimate product questions about outdoor heating furniture, capacity specifications, and safety features are ALWAYS appropriate for a furniture store assistant
      - Image-based product searches where users upload images to find similar items are core shopping functionality and should ALWAYS be allowed
