models:
  - type: content_safety
    engine: nim
    model: nvidia/llama-3.1-nemoguard-8b-content-safety
    parameters:
      base_url: https://api.build.nvidia.com/v1

  - type: topic_control
    engine: nim
    model: nvidia/llama-3.1-nemoguard-8b-topic-control
    parameters:
      base_url: https://api.build.nvidia.com/v1 