version: "3.8"

services:
  chain-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chain-server
    ports:
      - "8000:8000"
    environment:
      - LLM_API_KEY=${LLM_API_KEY}
      - CATALOG_RETRIEVER_URL=http://catalog-retriever:8000
      - MEMORY_RETRIEVER_URL=http://memory-retriever:8000
      - RAILS_URL=http://rails:8000
    networks:
      - shopping-network

networks:
  shopping-network:
    driver: bridge
